#!/bin/bash

output() {
    local emotion="$1"

    clear
    echo ==========================
    echo "  ,~."
    echo " ($(python3 -c "from emote import gen_"$emotion"; print(gen_"$emotion"())"))"
    echo "//-=-\\\\"
    echo "(\_=_/)"
    echo " ^^ ^^"
}

PS3="Enter a number: "

select option in Game-Selection Quit;
do
    case $option in
        Game-Selection)
            echo hi
            ;;
        Quit)
            echo bye
            ;;
        *)
            echo idiot
            ;;
    esac
done